# Generated by Django 6.0 on 2026-01-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=32, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('sub_industry', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand_voice', models.TextField(blank=True, null=True)),
                ('business_model', models.TextField(blank=True, null=True)),
                ('hq_country', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('employee_count', models.TextField(blank=True, null=True)),
                ('revenue_range', models.TextField(blank=True, null=True)),
                ('operating_regions', models.JSONField(blank=True, default=list, null=True)),
                ('tone_preferences', models.JSONField(blank=True, default=dict, null=True)),
                ('services', models.JSONField(blank=True, default=list, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('hqcity', models.CharField(blank=True, max_length=100, null=True)),
                ('hqstate', models.CharField(blank=True, max_length=100, null=True)),
                ('hqcountry', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_profiles',
            },
        ),
    ]
