# Generated by Django 5.2.9 on 2026-04-18 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_campaign_lead_list_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_id', models.CharField(max_length=36)),
                ('step_order', models.IntegerField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_from', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('replied', 'Replied'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'sent_emails',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('interested', 'Interested'), ('not_interested', 'Not Interested')], max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.sentemail')),
            ],
            options={
                'db_table': 'email_replies',
                'ordering': ['-received_at'],
            },
        ),
    ]
