# Generated by Django 5.2.9 on 2026-08-20 06:53

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_aiprompttemplateversion_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='state',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
