"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file into environment
load_dotenv(BASE_DIR / ".env")

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
SQUIBB_DOMAIN_URL = os.getenv("SQUIBB_DOMAIN_URL", "https://test-ai.squibb.ai")

# EC2 server URL — change only this in .env when the IP changes
SERVER_URL = os.getenv("SERVER_URL", "http://localhost:8000")

# Gmail SMTP settings (fallback for system emails)
GMAIL_USER = os.getenv("GMAIL_USER", "")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD", "")

# Google OAuth2 — per-user Gmail sending
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI", f"{os.getenv('SERVER_URL', 'http://localhost:8000')}/api/auth/gmail/callback/")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
_DEV_ONLY_SECRET_KEY = 'django-insecure-&59j64&t&nq)wz%rxghyve546z(_^vb)b*q9w7x63f0qyahtdj'
SECRET_KEY = os.getenv("SECRET_KEY", _DEV_ONLY_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# Matches the previous hardcoded default (False) unless overridden via env.
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")

if not DEBUG and SECRET_KEY == _DEV_ONLY_SECRET_KEY:
    raise RuntimeError(
        "SECRET_KEY environment variable must be set when DEBUG=False."
    )


_default_hosts = "localhost,127.0.0.1,.onrender.com"
ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", _default_hosts).split(",") if h.strip()]

STATIC_ROOT = BASE_DIR / "staticfiles"
AGENT_RUNTIME_ENABLED = True
AGENT_RUNTIME_TENANT_ALLOWLIST = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'authentication',
    'api',
    'agent_runtime',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'authentication.middleware.SingleUserMiddleware',  # attaches the default user — no login required
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

#
# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'lopes_leads_stg',
#         'USER': 'dev_lopes_agency',
#         'PASSWORD': 'Dev@Lopes.Agency!',
#         'HOST': '54.242.106.155',
#         # 'HOST' : '127.0.0.1',
#         'PORT': '3306',
#         'CONN_MAX_AGE': 600,
#         # 'PORT': '3307',
#         'OPTIONS': {
#             'init_command': "SET SESSION sql_mode='STRICT_TRANS_TABLES', SESSION wait_timeout=600",
#             'charset': 'utf8mb4',  # ✅ Ensures proper Unicode support
#             'ssl': False  # ❓ Set to `True` if SSL is required
#             'connect_timeout': 5,
#         }
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'lopes_leads_stg',
#         'USER': 'dev_lopes_agency',
#         'PASSWORD': 'Dev@Lopes.Agency!',  # NOTE: move to env var
#         'HOST': '54.242.106.155',
#         'PORT': '3306',
#         'CONN_MAX_AGE': 600,             # <── was 60
#         'OPTIONS': {
#             'init_command': "SET SESSION sql_mode='STRICT_TRANS_TABLES', SESSION wait_timeout=600",
#             'charset': 'utf8mb4',
#             'ssl': False,
#             'connect_timeout': 5,        # <── NEW: fail fast on DB connect
#         }
#     }
# }



# If DATABASE_URL is set (production — e.g. Neon Postgres), use it.
# Otherwise fall back to local SQLite for development — no external
# connection required. OPTIONS below mitigate "database is locked" errors
# under concurrent requests: WAL mode lets readers/writers coexist,
# IMMEDIATE transactions fail fast on write conflicts instead of upgrading
# mid-transaction, and timeout makes SQLite wait for a busy lock instead of
# raising immediately.
_database_url = os.getenv("DATABASE_URL")
if _database_url:
    import dj_database_url
    _ssl_require = os.getenv("DATABASE_SSL_REQUIRE", "True") == "True"
    DATABASES = {
        'default': dj_database_url.parse(_database_url, conn_max_age=600, ssl_require=_ssl_require)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 20,
                'transaction_mode': 'IMMEDIATE',
                'init_command': (
                    "PRAGMA journal_mode=WAL;"
                    "PRAGMA synchronous=NORMAL;"
                    "PRAGMA mmap_size=134217728;"
                    "PRAGMA journal_size_limit=67108864;"
                    "PRAGMA cache_size=2000;"
                ),
            },
        }
    }

# Previous: Personal TiDB Cloud DB (remote — kept for reference, do not commit real creds)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'test',
#         'USER': '3wC6Z3eqSkAUWrd.root',
#         'PASSWORD': 'z7ivBVNqFIE3TUoF',   # from TiDB dashboard
#         'HOST': 'gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com',
#         'PORT': '4000',
#         'OPTIONS': {
#             'ssl': {
#                 'ca': str(BASE_DIR / 'certs' / 'isrgrootx1.pem'),
#             },
#         },
#     }
# }
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Additional directories for static files
STATICFILES_DIRS = [
    BASE_DIR / "campaign_demo_frontend",
]

# WhiteNoise serves collected static files (e.g. Django admin CSS) directly
# from the app process — no separate static host needed on a free-tier deploy.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True") == "True"
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
_extra_cors = [SERVER_URL] if SERVER_URL not in ('http://localhost:8000', '') else []
_env_cors = [o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()]
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:8000',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'https://staging.squibb.ai',
    'https://test.dby989dgawwzr.amplifyapp.com',
    *_extra_cors,
    *_env_cors,
]

# CSRF: Django 4+ requires the scheme in trusted origins, and the deployed
# backend serves the frontend itself (same-origin), so SERVER_URL covers it.
CSRF_TRUSTED_ORIGINS = list({
    SERVER_URL,
    *(_env_cors or []),
    'https://*.onrender.com',
})

# If you need a permissive temporary setting, set to True during troubleshooting:
# CORS_ALLOW_ALL_ORIGINS = True
#
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '{levelname} {asctime} {module} {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': BASE_DIR / 'debug.log',
#             'formatter': 'verbose',
#         },
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'verbose',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file', 'console'],
#             'level': 'INFO',
#             'propagate': True,
#         },
#         'api': {  # Specific logger for our app
#             'handlers': ['file', 'console'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',  # <── was DEBUG
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'api': {
            'handlers': ['file', 'console'],
            'level': 'INFO',  # <── was DEBUG
            'propagate': True,
        },
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'authentication.drf_authentication.JWTMiddlewareAuthentication',
    ],  # Bridges JWT middleware user into DRF's request.user
    'DEFAULT_PERMISSION_CLASSES': [],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '1000/minute',
    }
}

# Custom User Model
AUTH_USER_MODEL = 'authentication.User'

# JWT Settings
JWT_SECRET_KEY = SECRET_KEY
JWT_ACCESS_TOKEN_LIFETIME = 1440  # minutes (24 hours)
JWT_REFRESH_TOKEN_LIFETIME = 7  # days
