# Generated by Django 5.2.9 on 2026-04-18 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('subdomain', models.TextField(blank=True, null=True)),
                ('ghl_location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ghl_status', models.CharField(blank=True, max_length=50, null=True)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('logo_url', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('account_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_users',
            },
        ),
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('credits_used', models.IntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage', to='authentication.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_usage',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(db_index=True, max_length=100)),
                ('feature_category', models.CharField(max_length=50)),
                ('first_used_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=1)),
                ('total_time_spent_seconds', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_usage', to='authentication.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature_usage',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_login_attempts',
                'indexes': [models.Index(fields=['email', 'attempted_at'], name='auth_login__email_c4fbee_idx'), models.Index(fields=['ip_address', 'attempted_at'], name='auth_login__ip_addr_0fb781_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('active_users_count', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_page_views', models.IntegerField(default=0)),
                ('total_api_calls', models.IntegerField(default=0)),
                ('leads_created', models.IntegerField(default=0)),
                ('campaigns_created', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('storage_used_mb', models.FloatField(default=0)),
                ('credits_used', models.IntegerField(default=0)),
                ('overage_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_metrics', to='authentication.organization')),
            ],
            options={
                'db_table': 'organization_usage',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=500, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_refresh_tokens',
            },
        ),
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('sessions_count', models.IntegerField(default=0)),
                ('total_time_seconds', models.IntegerField(default=0)),
                ('page_views_count', models.IntegerField(default=0)),
                ('actions_count', models.IntegerField(default=0)),
                ('features_used', models.JSONField(default=list)),
                ('engagement_score', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='authentication.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_engagement',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('actions_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('password_change', 'Password Change'), ('page_view', 'Page View'), ('dashboard_view', 'Dashboard View'), ('lead_search', 'Lead Search'), ('lead_view', 'Lead View'), ('lead_create', 'Lead Create'), ('lead_update', 'Lead Update'), ('lead_delete', 'Lead Delete'), ('lead_export', 'Lead Export'), ('lead_import', 'Lead Import'), ('campaign_create', 'Campaign Create'), ('campaign_view', 'Campaign View'), ('campaign_update', 'Campaign Update'), ('campaign_delete', 'Campaign Delete'), ('campaign_launch', 'Campaign Launch'), ('campaign_pause', 'Campaign Pause'), ('email_send', 'Email Send'), ('email_open', 'Email Open'), ('email_click', 'Email Click'), ('email_reply', 'Email Reply'), ('org_settings_view', 'Organization Settings View'), ('org_settings_update', 'Organization Settings Update'), ('user_invite', 'User Invite'), ('user_remove', 'User Remove'), ('billing_view', 'Billing View'), ('subscription_upgrade', 'Subscription Upgrade'), ('subscription_downgrade', 'Subscription Downgrade'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('api_call', 'API Call'), ('api_error', 'API Error'), ('file_upload', 'File Upload'), ('file_download', 'File Download'), ('search', 'Search'), ('filter_apply', 'Filter Apply'), ('export_data', 'Export Data'), ('settings_change', 'Settings Change')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.usersession')),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('referrer', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('time_on_page_seconds', models.IntegerField(blank=True, null=True)),
                ('scroll_depth_percent', models.IntegerField(blank=True, null=True)),
                ('interactions_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.usersession')),
            ],
            options={
                'db_table': 'page_views',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='auth_users_email_9c7e62_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_id', 'is_active'], name='auth_users_account_de8387_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['user', 'timestamp'], name='api_usage_user_id_8a1df0_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['organization', 'timestamp'], name='api_usage_organiz_1ed10f_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['endpoint', 'timestamp'], name='api_usage_endpoin_757c88_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'timestamp'], name='audit_logs_organiz_9c8c67_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['user', 'last_used_at'], name='feature_usa_user_id_b9638e_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['organization', 'feature_name'], name='feature_usa_organiz_471e7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featureusage',
            unique_together={('user', 'feature_name')},
        ),
        migrations.AddIndex(
            model_name='organizationusage',
            index=models.Index(fields=['organization', 'period_start'], name='organizatio_organiz_ae9d17_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['token', 'revoked'], name='auth_refres_token_887023_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user', 'revoked'], name='auth_refres_user_id_67b080_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['user', 'date'], name='user_engage_user_id_9c9dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['organization', 'date'], name='user_engage_organiz_0b1ae7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userengagement',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'started_at'], name='user_sessio_user_id_30ad4b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active'], name='user_sessio_is_acti_1b3cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_token'], name='user_sessio_session_baddb8_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'timestamp'], name='user_activi_user_id_d06d90_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_type', 'timestamp'], name='user_activi_activit_8de630_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['session', 'timestamp'], name='user_activi_session_9f95bf_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['resource_type', 'resource_id'], name='user_activi_resourc_b3d2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['user', 'viewed_at'], name='page_views_user_id_54e534_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['session', 'viewed_at'], name='page_views_session_ae15f0_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['url'], name='page_views_url_e9e913_idx'),
        ),
    ]
