# Generated by Django 5.2.9 on 2026-08-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_useremailconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmailConfig',
        ),
    ]
