from django.urls import path

from .views import (
    AgentConversationHistoryView,
    AgentConversationInitView,
    AgentConversationMessageView,
    AgentConversationResetView,
    AgentConversationStreamView,
    AgentPeopleSearchView,
    AgentLeadSelectionView,
    AgentCampaignCreateView,
    AgentCampaignApproveView,
    AgentCampaignSequenceView,
    AgentCampaignSendEmailView,
    AgentCampaignSendToLeadsView,
    AgentCampaignListView,
    AgentCampaignManageView,
    AgentEmailUpdateView,
    AgentInboxView,
    AgentEmailThreadView,
    AgentAddReplyView,
    AgentFetchRepliesView,
    AgentReplyToReplyView,
    AgentBusinessProfileView,
)

urlpatterns = [
    path("conversation/init/", AgentConversationInitView.as_view()),
    path("conversation/message/", AgentConversationMessageView.as_view()),
    path("conversation/stream/", AgentConversationStreamView.as_view()),
    path("conversation/history/", AgentConversationHistoryView.as_view()),
    path("conversation/reset/", AgentConversationResetView.as_view()),
    path("leads/search/people/", AgentPeopleSearchView.as_view()),
    path("leads/select/", AgentLeadSelectionView.as_view()),
    path("campaigns/create/", AgentCampaignCreateView.as_view()),
    path("campaigns/approve/", AgentCampaignApproveView.as_view()),
    path("campaigns/sequences/", AgentCampaignSequenceView.as_view()),
    path("campaigns/send-email/", AgentCampaignSendEmailView.as_view()),
    path("campaigns/send-to-leads/", AgentCampaignSendToLeadsView.as_view()),
    path("campaigns/list/", AgentCampaignListView.as_view()),
    path("campaigns/manage/", AgentCampaignManageView.as_view()),
    path("emails/update/", AgentEmailUpdateView.as_view()),
    path("inbox/", AgentInboxView.as_view()),
    path("inbox/thread/<str:sent_email_id>/", AgentEmailThreadView.as_view()),
    path("inbox/reply/", AgentAddReplyView.as_view()),
    path("inbox/fetch-replies/", AgentFetchRepliesView.as_view()),
    path("inbox/send-reply/", AgentReplyToReplyView.as_view()),
    path("business-profile/", AgentBusinessProfileView.as_view()),
]
