# Generated by Django 5.2.9 on 2026-08-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsourceexecutionaudit',
            name='session',
        ),
        migrations.RenameIndex(
            model_name='agentconversationevent',
            new_name='agent_conve_turn_id_9efe9a_idx',
            old_name='agent_runtime_turn_seq_idx',
        ),
        migrations.RenameIndex(
            model_name='agentconversationevent',
            new_name='agent_conve_event_t_5b0452_idx',
            old_name='agent_runtime_event_type_idx',
        ),
        migrations.DeleteModel(
            name='AgentSourceExecutionAudit',
        ),
    ]
