# Generated by Django 5.2.9 on 2026-08-20 06:53

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0002_remove_agentsourceexecutionaudit_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconversationevent',
            name='payload_json',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='agentconversationsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='agentconversationstate',
            name='state_json',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
