# api/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("health/", HealthCheckView.as_view(), name="health_check"),
    path("conversation/init/", InitConversationView.as_view()),
    path("conversation/message/", ConversationMessageView.as_view()),
    path("conversation/history/", ConversationHistoryView.as_view()),
    path("conversation/reset/", ResetConversationView.as_view()),
    path("leads/search/organizations/", OrganizationSearchView.as_view()),
    path("leads/search/people/", PeopleSearchView.as_view()),
    path('leads/search/runs/<str:run_id>/leads/', SearchRunResultsView.as_view()),
    path("leads/reveal/people/", PeopleRevealView.as_view()),
    path('leads/verify/lead/', LeadVerificationView.as_view()),
    path('business/extract/', BusinessProfileExtractView.as_view()),
    path('recommendations/prompts/', PromptRecommendationView.as_view()),
    path('leads/score/', ScoreLeadView.as_view()),
    path('leads/icp/saved/', SavedSearchView.as_view()),
    # path('leads/icp/<str:saved_id>/run/', ICPRunSearchView.as_view(), name='icp_run_search'),
    path('leads/ai/parse/', AIQueryParseView.as_view()),
    path('leads/fetch/', LeadFetchView.as_view()),
    path('leads/upload/', LeadUploadView.as_view()),
    path('leads/merge/', LeadMergeView.as_view()),
    path('leads/mark-duplicate/', MarkDuplicateView.as_view()),
    path('leads/dedupe-groups/<str:group_id>/', DedupeGroupView.as_view()),
    path('leads/<str:lead_id>/', LeadDetailView.as_view()),
    path('leads/search/history/', SearchHistoryView.as_view(), name='search_history'),
    path('leads/search/status/<str:search_run_id>/', SearchStatusView.as_view(), name='search_status'),
    path('leads/filters/normalize/', FilterNormalizationView.as_view()),
    path('leads/filters/options/', FilterOptionsView.as_view()),
    path('leads/<str:lead_id>/notes/', LeadNoteView.as_view()),
    path('leads/<str:lead_id>/notes/<str:note_id>/', LeadNoteView.as_view()),
    path('leads/<str:lead_id>/events/', LeadTimelineView.as_view()),
    path('leads/bulk/actions/', BulkActionView.as_view()),
    path('leads/<str:lead_id>/crm/push/', CRMExportView.as_view()),
    path('ml/campaigns/clarify/', CampaignClarificationView.as_view()),
    path('ml/campaigns/generate/', CampaignGenerationView.as_view()),
    path('ml/emails/generate/', EmailGenerationView.as_view()),
    path('ml/emails/spam-analysis/', EmailSpamAnalysisView.as_view()),
    path('ml/emails/reply/', CampaignReplyGenerationView.as_view()),
    path('ml/emails/reply/understand/', ReplyUnderstandingView.as_view()),
    path('ml/emails/subject/', SubjectLineGenerationView.as_view()),
    path('ml/insights/', AIInsightsView.as_view(), name='ai_insights'),
    path('ai/context/build', AIContextBuildView.as_view(), name='ai_context_build'),
    path('ai/prompt-templates/', AIPromptTemplateListView.as_view(), name='prompt_template_list'),
    path('ai/prompt-templates/<str:template_id>/', AIPromptTemplateDetailView.as_view(), name='prompt_template_detail'),
    path('ai/prompt-templates/<str:template_id>/versions/', AIPromptTemplateVersionsView.as_view(), name='prompt_template_versions'),
    path('ai/prompt-templates/<str:template_id>/rollback/', AIPromptTemplateRollbackView.as_view(), name='prompt_template_rollback'),
    path('ml/emails/contextual-followup/', ContextualFollowUpView.as_view(), name='contextual_followup'),
    path('campaigns/send-email/', SendCampaignEmailView.as_view(), name='send_campaign_email'),
    path('campaigns/send-to-leads/', SendToLeadsView.as_view(), name='send_to_leads'),
    path('campaigns/test-step/', TestCampaignStepView.as_view(), name='test_campaign_step'),
]